package j2cgen.models

sealed trait CaseClassGenerationFailure
case object ValueIsNull extends CaseClassGenerationFailure
case class JsonParseFailure(exception: Throwable) extends CaseClassGenerationFailure
case object InvalidRoot extends CaseClassGenerationFailure
case object ArrayTypeNotConsistent extends CaseClassGenerationFailure
case object ArrayEmpty extends CaseClassGenerationFailure
case object JsonContainsNoObjects extends CaseClassGenerationFailure
